/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

// Bit

public class Solution {
    public char findTheDifference(String s, String t) {
       char c = t.charAt(t.length() - 1);
       for (int i = 0; i < s.length(); i++) {
           c ^= s.charAt(i);
           c ^= t.charAt(i);
       }
       return c;
    }
}

// Map
public class Solution {
    public char findTheDifference(String s, String t) {
        if (s == null || t == null) {
            return '1';
        }
        Map<Character, Integer> map = new HashMap<>();
        for (int i = 0; i < s.length(); i++) {
            char curChar = s.charAt(i);
            if (!map.containsKey(curChar)) {
                map.put(curChar, 0);
            }
            map.put(curChar, map.get(curChar) + 1);
        }
        for (int i = 0; i < t.length(); i++) {
            char curChar = t.charAt(i);
            if (!map.containsKey(curChar)) {
                return curChar;
            }
            else if (map.get(curChar) == 0) {
                return curChar;
            }
            else {
                map.put(curChar, map.get(curChar) - 1);
            }
        }
        return '1';
    }
}
